// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: protobuf/heartbeat.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The heartbeat message
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      int64                  `protobuf:"varint,1,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_protobuf_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_protobuf_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

// The heartbeat acknowledgement message
type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      int64                  `protobuf:"varint,1,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_protobuf_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_protobuf_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatAck) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_protobuf_heartbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_heartbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_protobuf_heartbeat_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Address) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    bool                   `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_protobuf_heartbeat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_heartbeat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_heartbeat_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

var File_protobuf_heartbeat_proto protoreflect.FileDescriptor

const file_protobuf_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x18protobuf/heartbeat.proto\"'\n" +
	"\tHeartbeat\x12\x1a\n" +
	"\bsourceId\x18\x01 \x01(\x03R\bsourceId\"*\n" +
	"\fHeartbeatAck\x12\x1a\n" +
	"\bsourceId\x18\x01 \x01(\x03R\bsourceId\"1\n" +
	"\aAddress\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\"6\n" +
	"\x14RegistrationResponse\x12\x1e\n" +
	"\n" +
	"successful\x18\x01 \x01(\bR\n" +
	"successful2@\n" +
	"\x10HeartbeatService\x12,\n" +
	"\rSendHeartbeat\x12\n" +
	".Heartbeat\x1a\r.HeartbeatAck\"\x002L\n" +
	"\x13RegistrationService\x125\n" +
	"\x10RegisterFollower\x12\b.Address\x1a\x15.RegistrationResponse\"\x00B$Z\"github.com/joyrack/kv3600/protobufb\x06proto3"

var (
	file_protobuf_heartbeat_proto_rawDescOnce sync.Once
	file_protobuf_heartbeat_proto_rawDescData []byte
)

func file_protobuf_heartbeat_proto_rawDescGZIP() []byte {
	file_protobuf_heartbeat_proto_rawDescOnce.Do(func() {
		file_protobuf_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_heartbeat_proto_rawDesc), len(file_protobuf_heartbeat_proto_rawDesc)))
	})
	return file_protobuf_heartbeat_proto_rawDescData
}

var file_protobuf_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_heartbeat_proto_goTypes = []any{
	(*Heartbeat)(nil),            // 0: Heartbeat
	(*HeartbeatAck)(nil),         // 1: HeartbeatAck
	(*Address)(nil),              // 2: Address
	(*RegistrationResponse)(nil), // 3: RegistrationResponse
}
var file_protobuf_heartbeat_proto_depIdxs = []int32{
	0, // 0: HeartbeatService.SendHeartbeat:input_type -> Heartbeat
	2, // 1: RegistrationService.RegisterFollower:input_type -> Address
	1, // 2: HeartbeatService.SendHeartbeat:output_type -> HeartbeatAck
	3, // 3: RegistrationService.RegisterFollower:output_type -> RegistrationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_heartbeat_proto_init() }
func file_protobuf_heartbeat_proto_init() {
	if File_protobuf_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_heartbeat_proto_rawDesc), len(file_protobuf_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protobuf_heartbeat_proto_goTypes,
		DependencyIndexes: file_protobuf_heartbeat_proto_depIdxs,
		MessageInfos:      file_protobuf_heartbeat_proto_msgTypes,
	}.Build()
	File_protobuf_heartbeat_proto = out.File
	file_protobuf_heartbeat_proto_goTypes = nil
	file_protobuf_heartbeat_proto_depIdxs = nil
}
